@startuml
participant "EditorBridge" as Bridge
participant "engine" as E

Bridge -> E: updateTreeForFieldChange(document-as-tree, currentNodeID, \n editedField-Definition, changedValue)
E -> E: recursively register parent-nodes for backward-computation \n with attachParents(root)
E -> E: find currentNode in document-tree by currentNodeID
E -> E: handle potentials Transitions to different states \n and execute corresponding dependency-networks
E -> Bridge: return updated document-root
@enduml