@startuml
participant "EditorBridge" as Bridge
participant "engine" as E

Bridge -> E: updateTreeForFieldChange(costEngine, document, currentNodeID, \n editedField-Definition, changedValue)
E -> E: find currentNode in document-tree by currentNodeID
alt editedField-Definition has rules for backward-calculation
    E -> E: ResolveBackwardNode(currentNode, rules, targetFieldID, changedValue) \n -> lookup: update-backward.plantuml
    note left: rules are defined in CostEngine
    E -> E: replace recalculated current node in document-tree by currentNodeID
    E -> E: ComputeForward(document.root, rules) -> lookup: update-forward.plantuml
    E --> Bridge: return forward calculated document
else editedField-Definition has no rules for backward-calculation
    E -> E: change value of editedField in currentNode to changedValue
    E -> E: replace currentNode with changed values in document-tree (using CurrentNodeID)
    E -> E: ComputeForward(document.root, rules) -> lookup: update-forward.plantuml
    E --> Bridge: return forward calculated document
end
@enduml